server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push # URL de Loki

scrape_configs:
  - job_name: system-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log # Recolecta logs del sistema del host

  - job_name: docker
    pipeline_stages:
      - docker: {} # Parsea los logs en formato Docker JSON
    static_configs:
      - targets:
          - localhost
        labels:
          job: dockerlogs
          __path__: /var/lib/docker/containers/*/*log # Accede a los logs de los contenedores

    # Descubre contenedores Docker y aplica etiquetas útiles
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: container_name
      - source_labels: ['__meta_docker_image_name']
        target_label: image_name
      - source_labels: ['__meta_docker_container_id']
        target_label: container_id
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: service_name
      - source_labels: ['__meta_docker_container_label_com_docker_compose_project']
        target_label: project_name
